const companies = [
  {
    id: '21ImC8IUCp19m&QEfdBbg',
    company_name: "Raynor, Dietrich and O'Hara",
    industry: 'EDP Services',
    market_cap: '$2.67B',
    logo_img: 'http://dummyimage.com/135x100.png/cc0000/ffffff',
    street_address: '1856 Grim Street',
    state: 'IA',
    phone: '515-265-8284',
  },
  {
    id: '739bStMZKr28j&IV4PGuj',
    company_name: 'Gorczany-Kuhic',
    industry: 'Biotechnology: Electromedical & Electrotherapeutic Apparatus',
    market_cap: '$385.8M',
    logo_img: 'http://dummyimage.com/243x100.png/5fa2dd/ffffff',
    street_address: '970 Northwestern Crossing',
    state: 'SC',
    phone: '843-733-6484',
  },
  {
    id: '53FyQxFNZe88o&KGeWrae',
    company_name: 'Kiehn, Leuschke and Sawayn',
    industry: 'Industrial Specialties',
    market_cap: '$1.8B',
    logo_img: 'http://dummyimage.com/108x100.png/ff4444/ffffff',
    street_address: '73813 Everett Park',
    state: 'TN',
    phone: '901-785-3677',
  },
  {
    id: '48jJZAVGXs57k&P9nPRif',
    company_name: 'Abernathy-Baumbach',
    industry: 'Savings Institutions',
    market_cap: '$231.87M',
    logo_img: 'http://dummyimage.com/247x100.png/dddddd/000000',
    street_address: '45 Mariners Cove Park',
    state: 'TX',
    phone: '512-192-3551',
  },
  {
    id: '22E0GiH81b92r&B2uk7vf',
    company_name: 'Lemke LLC',
    industry: 'Major Banks',
    market_cap: '$383.64M',
    logo_img: 'http://dummyimage.com/197x100.png/dddddd/000000',
    street_address: '012 Acker Point',
    state: 'TX',
    phone: '361-755-5994',
  },
  {
    id: '49phRJKT8t50v&ONnHfjq',
    company_name: 'Bins, Hane and Weimann',
    industry: 'Property-Casualty Insurers',
    market_cap: '$982.38M',
    logo_img: 'http://dummyimage.com/105x100.png/dddddd/000000',
    street_address: '6 Pennsylvania Crossing',
    state: 'FL',
    phone: '863-641-1216',
  },
  {
    id: '43t3T9X09v76t&BInmQtp',
    company_name: 'Murphy-McDermott',
    industry: 'Finance: Consumer Services',
    market_cap: '$358.5M',
    logo_img: 'http://dummyimage.com/163x100.png/cc0000/ffffff',
    street_address: '056 Pawling Way',
    state: 'CA',
    phone: '213-350-9634',
  },
  {
    id: '50ZcOIAL0u65y&JKVYgbu',
    company_name: 'Zulauf-Bashirian',
    industry: 'Steel/Iron Ore',
    market_cap: '$4.61B',
    logo_img: 'http://dummyimage.com/242x100.png/5fa2dd/ffffff',
    street_address: '74037 Pepper Wood Trail',
    state: 'OK',
    phone: '405-514-1434',
  },
  {
    id: '13DSSYNH7d10c&IONcLii',
    company_name: 'Williamson Group',
    industry: 'Life Insurance',
    market_cap: '$36.08B',
    logo_img: 'http://dummyimage.com/145x100.png/cc0000/ffffff',
    street_address: '5 Ilene Road',
    state: 'NV',
    phone: '702-855-3190',
  },
  {
    id: '083jSxV4Kn27m&PKAJxpg',
    company_name: "O'Hara Group",
    industry: 'Transportation Services',
    market_cap: '$6.87B',
    logo_img: 'http://dummyimage.com/164x100.png/cc0000/ffffff',
    street_address: '92229 Hoard Hill',
    state: 'CA',
    phone: '916-222-0227',
  },
  {
    id: '632gWmIW6r17i&EQNsenm',
    company_name: 'Shanahan-Johnson',
    industry: 'Life Insurance',
    market_cap: '$3.08B',
    logo_img: 'http://dummyimage.com/101x100.png/cc0000/ffffff',
    street_address: '9266 Roth Avenue',
    state: 'NY',
    phone: '212-566-6532',
  },
  {
    id: '19NeYUPUEr56e&JOGhDqv',
    company_name: 'Greenfelder-Crist',
    industry: 'Steel/Iron Ore',
    market_cap: '$17.52B',
    logo_img: 'http://dummyimage.com/112x100.png/ff4444/ffffff',
    street_address: '852 Becker Way',
    state: 'MS',
    phone: '601-806-5353',
  },
  {
    id: '14fbAJQ2Fp19m&ADscUuc',
    company_name: 'Schumm, Hilpert and Schuppe',
    industry: 'Telecommunications Equipment',
    market_cap: '$31.13B',
    logo_img: 'http://dummyimage.com/120x100.png/5fa2dd/ffffff',
    street_address: '26580 Havey Crossing',
    state: 'MS',
    phone: '601-143-3576',
  },
  {
    id: '53AUR0WASu35y&WV5lGit',
    company_name: 'Turcotte and Sons',
    industry: 'Broadcasting',
    market_cap: '$3.57B',
    logo_img: 'http://dummyimage.com/101x100.png/ff4444/ffffff',
    street_address: '77 Goodland Junction',
    state: 'MO',
    phone: '417-666-3126',
  },
  {
    id: '13vtH7JC5b60r&X4i6enh',
    company_name: 'Rempel Group',
    industry: 'Computer Software: Prepackaged Software',
    market_cap: '$42.01M',
    logo_img: 'http://dummyimage.com/200x100.png/dddddd/000000',
    street_address: '3 Walton Plaza',
    state: 'NV',
    phone: '702-343-5442',
  },
  {
    id: '59mPV2KFKl58r&SAc66do',
    company_name: 'Morar-Kuphal',
    industry: 'Electric Utilities: Central',
    market_cap: '$1.69B',
    logo_img: 'http://dummyimage.com/126x100.png/ff4444/ffffff',
    street_address: '66 Independence Point',
    state: 'ID',
    phone: '208-795-5158',
  },
  {
    id: '23J6TgD8Kg94o&EM457ae',
    company_name: 'Mertz, Mayer and Hayes',
    industry: 'EDP Services',
    market_cap: '$13.37M',
    logo_img: 'http://dummyimage.com/142x100.png/cc0000/ffffff',
    street_address: '05894 Esker Center',
    state: 'UT',
    phone: '801-189-3934',
  },
  {
    id: '02yWGrT2Xg21s&IWgRycf',
    company_name: 'Bartoletti-Roob',
    industry: 'Industrial Machinery/Components',
    market_cap: '$219.92M',
    logo_img: 'http://dummyimage.com/171x100.png/dddddd/000000',
    street_address: '896 Gulseth Plaza',
    state: 'NH',
    phone: '603-192-4675',
  },
  {
    id: '400IDTJKAd95v&UZqdqls',
    company_name: 'Walsh, Lehner and Batz',
    industry: 'Shoe Manufacturing',
    market_cap: '$2.57B',
    logo_img: 'http://dummyimage.com/250x100.png/5fa2dd/ffffff',
    street_address: '78672 Londonderry Plaza',
    state: 'LA',
    phone: '318-700-7759',
  },
  {
    id: '76J2I6WFZm61y&IBlT8jf',
    company_name: 'Breitenberg-Sauer',
    industry: 'Major Pharmaceuticals',
    market_cap: '$114.27M',
    logo_img: 'http://dummyimage.com/127x100.png/cc0000/ffffff',
    street_address: '4532 Moland Point',
    state: 'KS',
    phone: '785-703-5547',
  },
  {
    id: '97SsVUFKHd64f&YMNjTvq',
    company_name: 'Rath-Connelly',
    industry: 'Building Products',
    market_cap: '$558.63M',
    logo_img: 'http://dummyimage.com/246x100.png/cc0000/ffffff',
    street_address: '4384 Bayside Parkway',
    state: 'TX',
    phone: '281-325-3412',
  },
  {
    id: '45tVCWH9Rm76b&Q5bX3dx',
    company_name: 'Thompson-Carter',
    industry: 'Major Pharmaceuticals',
    market_cap: '$108.91M',
    logo_img: 'http://dummyimage.com/159x100.png/ff4444/ffffff',
    street_address: '72957 Waubesa Center',
    state: 'FL',
    phone: '321-732-3216',
  },
  {
    id: '577bJcR33f45p&Z5q3cpq',
    company_name: 'Lemke, Bogisich and Ernser',
    industry: 'Electric Utilities: Central',
    market_cap: '$24.6B',
    logo_img: 'http://dummyimage.com/126x100.png/cc0000/ffffff',
    street_address: '05 Melody Lane',
    state: 'MN',
    phone: '763-855-2348',
  },
  {
    id: '07ipYvIP7e64j&TGglpts',
    company_name: 'Braun LLC',
    industry: 'Beverages (Production/Distribution)',
    market_cap: '$2.19B',
    logo_img: 'http://dummyimage.com/123x100.png/dddddd/000000',
    street_address: '2 Bay Drive',
    state: 'OH',
    phone: '330-130-0745',
  },
  {
    id: '428pIbM5Ss76y&VJpvxjq',
    company_name: 'Herman and Sons',
    industry: 'Investment Bankers/Brokers/Service',
    market_cap: '$82.28B',
    logo_img: 'http://dummyimage.com/121x100.png/dddddd/000000',
    street_address: '2205 Waywood Lane',
    state: 'DC',
    phone: '202-536-3286',
  },
  {
    id: '868hAXNXQe78f&XS9PSgn',
    company_name: 'Boyer Inc',
    industry: 'Industrial Machinery/Components',
    market_cap: '$22.2B',
    logo_img: 'http://dummyimage.com/105x100.png/ff4444/ffffff',
    street_address: '405 Forster Alley',
    state: 'FL',
    phone: '561-222-8752',
  },
  {
    id: '70f7ZcNATt29c&QFvRzng',
    company_name: 'Gutmann Group',
    industry: 'Beverages (Production/Distribution)',
    market_cap: '$17.31B',
    logo_img: 'http://dummyimage.com/217x100.png/cc0000/ffffff',
    street_address: '501 Kenwood Avenue',
    state: 'MO',
    phone: '314-192-3718',
  },
  {
    id: '04okEhJSNt44u&HBXpzao',
    company_name: 'Reichert-Thompson',
    industry: 'Major Chemicals',
    market_cap: '$29.54M',
    logo_img: 'http://dummyimage.com/242x100.png/5fa2dd/ffffff',
    street_address: '4 Blackbird Point',
    state: 'AZ',
    phone: '520-703-2550',
  },
  {
    id: '62dtX9VX9l88z&YV0Uzoz',
    company_name: 'Ebert Group',
    industry: 'Major Banks',
    market_cap: '$8.73B',
    logo_img: 'http://dummyimage.com/238x100.png/dddddd/000000',
    street_address: '83738 Waxwing Hill',
    state: 'NE',
    phone: '402-661-5992',
  },
  {
    id: '910qTyP49b71q&MPlU6mr',
    company_name: 'Wyman-Christiansen',
    industry: 'Home Furnishings',
    market_cap: '$2.61B',
    logo_img: 'http://dummyimage.com/169x100.png/cc0000/ffffff',
    street_address: '351 Autumn Leaf Place',
    state: 'IN',
    phone: '812-722-2330',
  },
  {
    id: '08x4TaL28u78k&AJtTfsw',
    company_name: 'Bergstrom and Sons',
    industry: 'Major Banks',
    market_cap: '$400.41M',
    logo_img: 'http://dummyimage.com/100x100.png/ff4444/ffffff',
    street_address: '02 Village Trail',
    state: 'FL',
    phone: '941-562-6619',
  },
  {
    id: '309dFEHPPk45a&QDWxwqp',
    company_name: 'Nienow and Sons',
    industry: 'Consumer Electronics/Appliances',
    market_cap: '$510.83M',
    logo_img: 'http://dummyimage.com/214x100.png/ff4444/ffffff',
    street_address: '2969 Cordelia Trail',
    state: 'NY',
    phone: '212-534-7373',
  },
  {
    id: '331hJRPXYr79o&M7G2bfr',
    company_name: 'Romaguera-Block',
    industry: 'Real Estate Investment Trusts',
    market_cap: '$3.51B',
    logo_img: 'http://dummyimage.com/218x100.png/5fa2dd/ffffff',
    street_address: '6173 Forster Way',
    state: 'WA',
    phone: '360-801-9884',
  },
  {
    id: '62KzUgS82v99c&CAtvbch',
    company_name: 'Little, McGlynn and Grady',
    industry: 'Major Pharmaceuticals',
    market_cap: '$30.59M',
    logo_img: 'http://dummyimage.com/129x100.png/cc0000/ffffff',
    street_address: '8 Superior Court',
    state: 'DC',
    phone: '202-406-8482',
  },
  {
    id: '47kfPhGVLn25p&GT0k6pk',
    company_name: 'Weber LLC',
    industry: 'Major Banks',
    market_cap: '$300.24M',
    logo_img: 'http://dummyimage.com/132x100.png/5fa2dd/ffffff',
    street_address: '5819 Bartillon Pass',
    state: 'AL',
    phone: '205-598-7487',
  },
  {
    id: '04R7LXR6Ia65a&VZCGyih',
    company_name: 'Renner, Boyle and Homenick',
    industry: 'Hospital/Nursing Management',
    market_cap: '$11.13B',
    logo_img: 'http://dummyimage.com/227x100.png/ff4444/ffffff',
    street_address: '1561 Mifflin Parkway',
    state: 'TX',
    phone: '214-997-0755',
  },
  {
    id: '23tCDNIO6r20t&ATAVNof',
    company_name: 'Jast, Kerluke and Homenick',
    industry: 'Medical Specialities',
    market_cap: '$14.5B',
    logo_img: 'http://dummyimage.com/204x100.png/dddddd/000000',
    street_address: '9 Barby Pass',
    state: 'MO',
    phone: '314-902-9974',
  },
  {
    id: '25MAF3H85e61z&Z5XF6iv',
    company_name: 'Larkin and Sons',
    industry: 'Food Distributors',
    market_cap: '$387.37M',
    logo_img: 'http://dummyimage.com/139x100.png/dddddd/000000',
    street_address: '5 Dahle Crossing',
    state: 'WV',
    phone: '304-715-6168',
  },
  {
    id: '73umWxKTVi38d&J5mbqmx',
    company_name: 'Gusikowski LLC',
    industry: 'Real Estate Investment Trusts',
    market_cap: '$805.82M',
    logo_img: 'http://dummyimage.com/227x100.png/ff4444/ffffff',
    street_address: '72360 Florence Park',
    state: 'OK',
    phone: '405-230-6394',
  },
  {
    id: '67NNCAFZMz76g&JTWWEoi',
    company_name: 'Ortiz LLC',
    industry: 'Hotels/Resorts',
    market_cap: '$3.75B',
    logo_img: 'http://dummyimage.com/128x100.png/ff4444/ffffff',
    street_address: '27568 Lukken Park',
    state: 'NE',
    phone: '712-238-8004',
  },
  {
    id: '08r7D1L16m59w&UVWnqcy',
    company_name: 'Rohan Inc',
    industry: 'Business Services',
    market_cap: '$28.99M',
    logo_img: 'http://dummyimage.com/247x100.png/cc0000/ffffff',
    street_address: '3 Sunbrook Hill',
    state: 'AK',
    phone: '907-948-6152',
  },
  {
    id: '96GeBHQRDr38c&D0PgGlr',
    company_name: 'Konopelski-Schinner',
    industry: 'Automotive Aftermarket',
    market_cap: '$1.28B',
    logo_img: 'http://dummyimage.com/113x100.png/cc0000/ffffff',
    street_address: '462 Corscot Pass',
    state: 'TX',
    phone: '940-107-4664',
  },
  {
    id: '46knS6KGSv42k&M6Kysyi',
    company_name: 'Maggio, Brekke and Braun',
    industry: 'Major Chemicals',
    market_cap: '$477.6M',
    logo_img: 'http://dummyimage.com/158x100.png/cc0000/ffffff',
    street_address: '902 Ryan Parkway',
    state: 'MN',
    phone: '651-178-7187',
  },
  {
    id: '83LZWkH80z52j&N6qVGlj',
    company_name: "Dooley-O'Keefe",
    industry: 'Other Consumer Services',
    market_cap: '$1.83B',
    logo_img: 'http://dummyimage.com/232x100.png/dddddd/000000',
    street_address: '2 Carey Plaza',
    state: 'TX',
    phone: '806-322-7982',
  },
  {
    id: '27X1B7HT4h19s&HUZmXek',
    company_name: 'Schroeder, Senger and Lemke',
    industry: 'Major Pharmaceuticals',
    market_cap: '$48.4M',
    logo_img: 'http://dummyimage.com/126x100.png/ff4444/ffffff',
    street_address: '774 Russell Plaza',
    state: 'NC',
    phone: '704-114-6161',
  },
  {
    id: '51Z8EhVQEm53v&KYb7ied',
    company_name: 'Hills, Moore and Heathcote',
    industry: 'Investment Bankers/Brokers/Service',
    market_cap: '$14.98B',
    logo_img: 'http://dummyimage.com/176x100.png/5fa2dd/ffffff',
    street_address: '13 Daystar Trail',
    state: 'NY',
    phone: '212-956-8619',
  },
  {
    id: '59KjVfWVZv59g&JTaXorq',
    company_name: 'Haag-White',
    industry: 'Property-Casualty Insurers',
    market_cap: '$49.09M',
    logo_img: 'http://dummyimage.com/174x100.png/5fa2dd/ffffff',
    street_address: '7 Haas Court',
    state: 'KY',
    phone: '502-515-6821',
  },
  {
    id: '79xnY9ZSHw42x&OGcsmsz',
    company_name: 'Brakus, Dach and Yost',
    industry: 'Services-Misc. Amusement & Recreation',
    market_cap: '$40.17M',
    logo_img: 'http://dummyimage.com/154x100.png/5fa2dd/ffffff',
    street_address: '034 Crest Line Lane',
    state: 'TX',
    phone: '512-575-0461',
  },
  {
    id: '52FpTXTY4a98l&B3jbfde',
    company_name: 'Effertz Group',
    industry: 'Investment Bankers/Brokers/Service',
    market_cap: '$112.63M',
    logo_img: 'http://dummyimage.com/201x100.png/ff4444/ffffff',
    street_address: '12533 Hayes Drive',
    state: 'TX',
    phone: '956-560-0844',
  },
  {
    id: '08RkRmSV3s48w&DXngexw',
    company_name: 'Weber, Schuppe and Cummerata',
    industry: 'Banks',
    market_cap: '$153.96M',
    logo_img: 'http://dummyimage.com/217x100.png/5fa2dd/ffffff',
    street_address: '50 Northfield Trail',
    state: 'NY',
    phone: '585-733-4294',
  },
  {
    id: '50mfIHZTKm51o&K2JTTih',
    company_name: 'McGlynn and Sons',
    industry: 'Oilfield Services/Equipment',
    market_cap: '$141.67M',
    logo_img: 'http://dummyimage.com/174x100.png/dddddd/000000',
    street_address: '5 Spohn Alley',
    state: 'NY',
    phone: '518-673-9771',
  },
  {
    id: '01fsNyJEDs52b&X0kXMwm',
    company_name: 'Powlowski, Walter and Moore',
    industry: 'Industrial Specialties',
    market_cap: '$70.59M',
    logo_img: 'http://dummyimage.com/180x100.png/ff4444/ffffff',
    street_address: '4445 Grasskamp Park',
    state: 'IL',
    phone: '312-204-8382',
  },
  {
    id: '73idM7QP4o66t&JMmL4ai',
    company_name: 'Stamm LLC',
    industry: 'Industrial Machinery/Components',
    market_cap: '$204.83M',
    logo_img: 'http://dummyimage.com/211x100.png/5fa2dd/ffffff',
    street_address: '088 Shasta Trail',
    state: 'IN',
    phone: '765-479-0400',
  },
  {
    id: '93srUSL1Yt42j&KSlsVpb',
    company_name: 'Wunsch, Schmitt and Renner',
    industry: 'Industrial Machinery/Components',
    market_cap: '$708.76M',
    logo_img: 'http://dummyimage.com/220x100.png/5fa2dd/ffffff',
    street_address: '4948 Esker Point',
    state: 'MO',
    phone: '314-138-3222',
  },
  {
    id: '29CPLQZX7l27l&ATXLyth',
    company_name: 'Orn-Murphy',
    industry: 'Auto Parts:O.E.M.',
    market_cap: '$506.02M',
    logo_img: 'http://dummyimage.com/153x100.png/dddddd/000000',
    street_address: '38026 Aberg Avenue',
    state: 'GA',
    phone: '404-249-0574',
  },
  {
    id: '70EADpH7Hg39g&BUqA6cz',
    company_name: 'Stoltenberg Inc',
    industry: 'Restaurants',
    market_cap: '$6.31M',
    logo_img: 'http://dummyimage.com/238x100.png/ff4444/ffffff',
    street_address: '17 Village Point',
    state: 'AL',
    phone: '256-829-9266',
  },
  {
    id: '43h5VGVUEi65v&BNxpCtd',
    company_name: 'Hoppe Group',
    industry: 'Consumer Specialties',
    market_cap: '$1.51B',
    logo_img: 'http://dummyimage.com/171x100.png/5fa2dd/ffffff',
    street_address: '78 Straubel Pass',
    state: 'PA',
    phone: '814-372-8547',
  },
  {
    id: '87N2BZIELb65b&MOChEjy',
    company_name: 'Donnelly, Schroeder and Price',
    industry: 'Steel/Iron Ore',
    market_cap: '$790.37M',
    logo_img: 'http://dummyimage.com/236x100.png/5fa2dd/ffffff',
    street_address: '635 Springs Park',
    state: 'WI',
    phone: '608-744-3462',
  },
  {
    id: '50uwRmJP0r92g&XLGoIlf',
    company_name: 'Mraz LLC',
    industry: 'Radio And Television Broadcasting And Communications Equipment',
    market_cap: '$17.76M',
    logo_img: 'http://dummyimage.com/238x100.png/dddddd/000000',
    street_address: '44231 Fisk Way',
    state: 'TX',
    phone: '325-443-9717',
  },
  {
    id: '04CXGBD95p64j&GFsHzvf',
    company_name: 'Fay-Reilly',
    industry: 'Wholesale Distributors',
    market_cap: '$99.14M',
    logo_img: 'http://dummyimage.com/240x100.png/5fa2dd/ffffff',
    street_address: '0080 Oak Valley Crossing',
    state: 'TX',
    phone: '682-794-4375',
  },
  {
    id: '80IvXlPHJo49z&FHORuqr',
    company_name: 'Renner, Ernser and Bailey',
    industry: 'Real Estate Investment Trusts',
    market_cap: '$80.86M',
    logo_img: 'http://dummyimage.com/203x100.png/5fa2dd/ffffff',
    street_address: '16928 New Castle Circle',
    state: 'FL',
    phone: '786-558-4780',
  },
  {
    id: '85bSJLHJ5s79o&DDEMGej',
    company_name: 'Lemke-Doyle',
    industry: 'Motor Vehicles',
    market_cap: '$1.22B',
    logo_img: 'http://dummyimage.com/201x100.png/dddddd/000000',
    street_address: '95 Dunning Pass',
    state: 'PA',
    phone: '215-384-3715',
  },
  {
    id: '56FbAoF7Td09a&WO4mOlk',
    company_name: 'Padberg, Jakubowski and Wiza',
    industry: 'EDP Services',
    market_cap: '$2.26B',
    logo_img: 'http://dummyimage.com/118x100.png/cc0000/ffffff',
    street_address: '99 Portage Road',
    state: 'OH',
    phone: '216-355-3697',
  },
  {
    id: '04hlFAJB4f44l&BTr83se',
    company_name: 'Stracke, Volkman and Auer',
    industry: 'Electrical Products',
    market_cap: '$496.43M',
    logo_img: 'http://dummyimage.com/160x100.png/dddddd/000000',
    street_address: '646 Nova Lane',
    state: 'AL',
    phone: '334-549-5025',
  },
  {
    id: '83okZLL6Yw26b&X41lsvr',
    company_name: 'Sporer Inc',
    industry: 'Fluid Controls',
    market_cap: '$3.56B',
    logo_img: 'http://dummyimage.com/151x100.png/ff4444/ffffff',
    street_address: '152 Weeping Birch Park',
    state: 'GA',
    phone: '478-247-6546',
  },
  {
    id: '33QARoW9Jk32a&LWSjenb',
    company_name: 'Reichel Inc',
    industry: 'Major Banks',
    market_cap: '$45.79B',
    logo_img: 'http://dummyimage.com/124x100.png/5fa2dd/ffffff',
    street_address: '4490 Kim Terrace',
    state: 'NJ',
    phone: '862-833-0247',
  },
  {
    id: '42BRYEJNWl10r&N0WA7ol',
    company_name: 'Bosco, Beahan and Casper',
    industry: 'Restaurants',
    market_cap: '$14.34B',
    logo_img: 'http://dummyimage.com/235x100.png/ff4444/ffffff',
    street_address: '9849 Jenifer Pass',
    state: 'MI',
    phone: '313-752-3597',
  },
  {
    id: '056qHnE87u36l&KDxSwxn',
    company_name: 'Dickinson, Bosco and Runte',
    industry: 'Farming/Seeds/Milling',
    market_cap: '$222.06M',
    logo_img: 'http://dummyimage.com/241x100.png/dddddd/000000',
    street_address: '0 Carioca Junction',
    state: 'NC',
    phone: '704-776-3843',
  },
  {
    id: '79aZGAET2g29f&VJis6nj',
    company_name: 'Wiegand, Runolfsdottir and Waelchi',
    industry: 'Investment Managers',
    market_cap: '$637.26M',
    logo_img: 'http://dummyimage.com/156x100.png/5fa2dd/ffffff',
    street_address: '4418 Fallview Court',
    state: 'AZ',
    phone: '480-793-5782',
  },
  {
    id: '9986DuWY1j97c&U0GLgio',
    company_name: 'Gottlieb-Gerhold',
    industry: 'Real Estate',
    market_cap: '$2.15B',
    logo_img: 'http://dummyimage.com/218x100.png/cc0000/ffffff',
    street_address: '6934 Trailsway Pass',
    state: 'MN',
    phone: '651-517-6680',
  },
  {
    id: '37wmWQCCZp61x&TOjaIzn',
    company_name: 'Christiansen-Greenfelder',
    industry: 'Military/Government/Technical',
    market_cap: '$2.7B',
    logo_img: 'http://dummyimage.com/214x100.png/5fa2dd/ffffff',
    street_address: '521 Schurz Circle',
    state: 'AR',
    phone: '501-505-6479',
  },
  {
    id: '21IyLCU9Mj23n&YFs0zno',
    company_name: 'Blanda-Stanton',
    industry: 'Industrial Machinery/Components',
    market_cap: '$58.51M',
    logo_img: 'http://dummyimage.com/212x100.png/5fa2dd/ffffff',
    street_address: '109 Lakewood Trail',
    state: 'AZ',
    phone: '602-447-2517',
  },
  {
    id: '06gISyNBJz59v&KWDIAjb',
    company_name: 'Romaguera Inc',
    industry: 'Computer Software: Programming, Data Processing',
    market_cap: '$814.69M',
    logo_img: 'http://dummyimage.com/234x100.png/cc0000/ffffff',
    street_address: '29 Hintze Street',
    state: 'VA',
    phone: '540-121-0224',
  },
  {
    id: '46s1XpUKKn53u&XWT5vir',
    company_name: 'Strosin, Lebsack and Walter',
    industry: 'Restaurants',
    market_cap: '$1.38B',
    logo_img: 'http://dummyimage.com/127x100.png/cc0000/ffffff',
    street_address: '287 Arapahoe Alley',
    state: 'DC',
    phone: '202-841-0239',
  },
  {
    id: '92AWJaTG8d09a&V8MOTew',
    company_name: 'Altenwerth, Upton and Erdman',
    industry: 'Major Banks',
    market_cap: '$640.53M',
    logo_img: 'http://dummyimage.com/118x100.png/dddddd/000000',
    street_address: '18 Johnson Point',
    state: 'WV',
    phone: '304-134-5160',
  },
  {
    id: '94cWX6LWOf35e&IP5WRix',
    company_name: 'Keeling-Donnelly',
    industry: 'Major Pharmaceuticals',
    market_cap: '$64.12M',
    logo_img: 'http://dummyimage.com/208x100.png/cc0000/ffffff',
    street_address: '8 Northridge Court',
    state: 'MN',
    phone: '612-458-9606',
  },
  {
    id: '32uYVnR21e34g&CWi72go',
    company_name: 'Green-Connelly',
    industry: 'Oil & Gas Production',
    market_cap: '$22.46M',
    logo_img: 'http://dummyimage.com/243x100.png/ff4444/ffffff',
    street_address: '7348 Oak Court',
    state: 'TX',
    phone: '972-180-1203',
  },
  {
    id: '37zoFSZ0Qp21b&KIdHmia',
    company_name: 'Farrell-Dickens',
    industry: 'Major Pharmaceuticals',
    market_cap: '$725.05M',
    logo_img: 'http://dummyimage.com/140x100.png/5fa2dd/ffffff',
    street_address: '40 Rieder Plaza',
    state: 'NY',
    phone: '315-719-6918',
  },
  {
    id: '0196K6DELx87x&C16Mxue',
    company_name: 'Huel-Kulas',
    industry: 'Property-Casualty Insurers',
    market_cap: '$1.14B',
    logo_img: 'http://dummyimage.com/205x100.png/cc0000/ffffff',
    street_address: '9768 Garrison Pass',
    state: 'IN',
    phone: '765-245-9588',
  },
  {
    id: '49uTYIALKv36c&IMfFGho',
    company_name: 'Schmidt-Sporer',
    industry: 'Computer Software: Prepackaged Software',
    market_cap: '$1.61B',
    logo_img: 'http://dummyimage.com/205x100.png/dddddd/000000',
    street_address: '8 Johnson Way',
    state: 'GA',
    phone: '706-374-9639',
  },
  {
    id: '98TkZdFYDm27z&SEP61wf',
    company_name: 'Nader Inc',
    industry: 'Hospital/Nursing Management',
    market_cap: '$1.71B',
    logo_img: 'http://dummyimage.com/149x100.png/cc0000/ffffff',
    street_address: '442 Arizona Road',
    state: 'TX',
    phone: '512-745-8145',
  },
  {
    id: '75thXYSTSt13u&R9VIEtb',
    company_name: 'Kilback and Sons',
    industry: 'Pollution Control Equipment',
    market_cap: '$59.07M',
    logo_img: 'http://dummyimage.com/120x100.png/dddddd/000000',
    street_address: '50095 Waxwing Place',
    state: 'TX',
    phone: '512-434-7023',
  },
  {
    id: '01HaCOUE4u11b&G4NpYns',
    company_name: 'Windler-Heathcote',
    industry: 'Industrial Machinery/Components',
    market_cap: '$58.51M',
    logo_img: 'http://dummyimage.com/207x100.png/5fa2dd/ffffff',
    street_address: '63635 Center Court',
    state: 'PA',
    phone: '724-544-1555',
  },
  {
    id: '24ObOmV14d68x&CKRzzdu',
    company_name: 'Casper, Casper and Hayes',
    industry: 'Computer Software: Prepackaged Software',
    market_cap: '$10.41B',
    logo_img: 'http://dummyimage.com/150x100.png/5fa2dd/ffffff',
    street_address: '834 Killdeer Avenue',
    state: 'PA',
    phone: '215-728-0144',
  },
  {
    id: '78VLC4RK7u54c&E4cYDxs',
    company_name: 'Hahn-Mills',
    industry: 'Department/Specialty Retail Stores',
    market_cap: '$29.03B',
    logo_img: 'http://dummyimage.com/166x100.png/ff4444/ffffff',
    street_address: '2 Oxford Pass',
    state: 'MA',
    phone: '508-287-4425',
  },
  {
    id: '2721TSRQKs74b&ITIsPwk',
    company_name: 'MacGyver-Schuppe',
    industry: 'Business Services',
    market_cap: '$312.5M',
    logo_img: 'http://dummyimage.com/100x100.png/dddddd/000000',
    street_address: '49786 Acker Hill',
    state: 'DC',
    phone: '202-394-8114',
  },
  {
    id: '02iEPuHXUe30m&WAjyazb',
    company_name: 'Williamson-McGlynn',
    industry: 'Marine Transportation',
    market_cap: '$3.55M',
    logo_img: 'http://dummyimage.com/244x100.png/ff4444/ffffff',
    street_address: '6370 Dixon Lane',
    state: 'VA',
    phone: '804-730-1104',
  },
  {
    id: '62K5FzHLTz46t&MRCe0sm',
    company_name: 'Douglas-Wiegand',
    industry: 'Movies/Entertainment',
    market_cap: '$642.98M',
    logo_img: 'http://dummyimage.com/117x100.png/cc0000/ffffff',
    street_address: '1 Continental Pass',
    state: 'CA',
    phone: '213-806-4752',
  },
  {
    id: '98ZfSVVC8q34w&VJ36qcx',
    company_name: 'Sporer LLC',
    industry: 'Metal Fabrications',
    market_cap: '$1.49B',
    logo_img: 'http://dummyimage.com/167x100.png/ff4444/ffffff',
    street_address: '41956 Anderson Circle',
    state: 'CA',
    phone: '213-776-0197',
  },
  {
    id: '23rRVxB4Cg76j&J3dMyal',
    company_name: 'Larkin Group',
    industry: 'Military/Government/Technical',
    market_cap: '$5.08B',
    logo_img: 'http://dummyimage.com/121x100.png/cc0000/ffffff',
    street_address: '5 Thompson Drive',
    state: 'TX',
    phone: '915-454-2099',
  },
  {
    id: '87XnAhJDFp70e&Q4jwgxs',
    company_name: 'Boehm and Sons',
    industry: 'Major Banks',
    market_cap: '$20.32B',
    logo_img: 'http://dummyimage.com/223x100.png/dddddd/000000',
    street_address: '8 Fuller Place',
    state: 'CA',
    phone: '559-119-4104',
  },
  {
    id: '40v8F0NIYr72v&ZCQETgf',
    company_name: 'Crist-Shields',
    industry: 'Major Banks',
    market_cap: '$1.89B',
    logo_img: 'http://dummyimage.com/180x100.png/cc0000/ffffff',
    street_address: '802 Ludington Street',
    state: 'NY',
    phone: '716-648-8338',
  },
  {
    id: '39RpBmNQUi74u&MBAsNvn',
    company_name: 'Towne and Sons',
    industry: 'Industrial Specialties',
    market_cap: '$154.26M',
    logo_img: 'http://dummyimage.com/200x100.png/ff4444/ffffff',
    street_address: '87 Truax Lane',
    state: 'TX',
    phone: '214-109-9551',
  },
  {
    id: '72GQBpJOFv27j&FYQJLra',
    company_name: 'Hettinger and Sons',
    industry: 'Natural Gas Distribution',
    market_cap: '$4.55B',
    logo_img: 'http://dummyimage.com/145x100.png/cc0000/ffffff',
    street_address: '8165 Erie Terrace',
    state: 'TX',
    phone: '713-371-7746',
  },
  {
    id: '39ckZ3XONk29k&XBE15zr',
    company_name: 'Considine, Hane and Olson',
    industry: 'Railroads',
    market_cap: '$212.14M',
    logo_img: 'http://dummyimage.com/247x100.png/cc0000/ffffff',
    street_address: '5583 Center Avenue',
    state: 'AZ',
    phone: '602-734-1268',
  },
];
const financials = [
  {
    company_id: '21ImC8IUCp19m&QEfdBbg',
    quarter: 'Q122',
    cogs: 87,
    profit_margin: 2.328,
    revenue: 89.02536,
  },
  {
    company_id: '739bStMZKr28j&IV4PGuj',
    quarter: 'Q122',
    cogs: 85,
    profit_margin: 4.716,
    revenue: 89.0086,
  },
  {
    company_id: '53FyQxFNZe88o&KGeWrae',
    quarter: 'Q122',
    cogs: 127,
    profit_margin: 10.479,
    revenue: 140.30833,
  },
  {
    company_id: '48jJZAVGXs57k&P9nPRif',
    quarter: 'Q122',
    cogs: 132,
    profit_margin: 10.035,
    revenue: 145.2462,
  },
  {
    company_id: '22E0GiH81b92r&B2uk7vf',
    quarter: 'Q122',
    cogs: 86,
    profit_margin: 3.575,
    revenue: 89.0745,
  },
  {
    company_id: '49phRJKT8t50v&ONnHfjq',
    quarter: 'Q122',
    cogs: 14,
    profit_margin: 5.417,
    revenue: 14.75838,
  },
  {
    company_id: '43t3T9X09v76t&BInmQtp',
    quarter: 'Q122',
    cogs: 97,
    profit_margin: 1.855,
    revenue: 98.79935,
  },
  {
    company_id: '50ZcOIAL0u65y&JKVYgbu',
    quarter: 'Q122',
    cogs: 20,
    profit_margin: 10.723,
    revenue: 22.1446,
  },
  {
    company_id: '13DSSYNH7d10c&IONcLii',
    quarter: 'Q122',
    cogs: 75,
    profit_margin: 0.164,
    revenue: 75.123,
  },
  {
    company_id: '083jSxV4Kn27m&PKAJxpg',
    quarter: 'Q122',
    cogs: 120,
    profit_margin: 3.481,
    revenue: 124.1772,
  },
  {
    company_id: '632gWmIW6r17i&EQNsenm',
    quarter: 'Q122',
    cogs: 72,
    profit_margin: 1.547,
    revenue: 73.11384,
  },
  {
    company_id: '19NeYUPUEr56e&JOGhDqv',
    quarter: 'Q122',
    cogs: 126,
    profit_margin: 0.547,
    revenue: 126.68922,
  },
  {
    company_id: '14fbAJQ2Fp19m&ADscUuc',
    quarter: 'Q122',
    cogs: 64,
    profit_margin: 9.386,
    revenue: 70.00704,
  },
  {
    company_id: '53AUR0WASu35y&WV5lGit',
    quarter: 'Q122',
    cogs: 36,
    profit_margin: 10.299,
    revenue: 39.70764,
  },
  {
    company_id: '13vtH7JC5b60r&X4i6enh',
    quarter: 'Q122',
    cogs: 82,
    profit_margin: 9.515,
    revenue: 89.8023,
  },
  {
    company_id: '59mPV2KFKl58r&SAc66do',
    quarter: 'Q122',
    cogs: 28,
    profit_margin: 11.746,
    revenue: 31.28888,
  },
  {
    company_id: '23J6TgD8Kg94o&EM457ae',
    quarter: 'Q122',
    cogs: 54,
    profit_margin: 7.7,
    revenue: 58.158,
  },
  {
    company_id: '02yWGrT2Xg21s&IWgRycf',
    quarter: 'Q122',
    cogs: 44,
    profit_margin: 5.301,
    revenue: 46.33244,
  },
  {
    company_id: '400IDTJKAd95v&UZqdqls',
    quarter: 'Q122',
    cogs: 111,
    profit_margin: 9.63,
    revenue: 121.6893,
  },
  {
    company_id: '76J2I6WFZm61y&IBlT8jf',
    quarter: 'Q122',
    cogs: 17,
    profit_margin: 11.296,
    revenue: 18.92032,
  },
  {
    company_id: '97SsVUFKHd64f&YMNjTvq',
    quarter: 'Q122',
    cogs: 127,
    profit_margin: 5.492,
    revenue: 133.97484,
  },
  {
    company_id: '45tVCWH9Rm76b&Q5bX3dx',
    quarter: 'Q122',
    cogs: 13,
    profit_margin: 8.741,
    revenue: 14.13633,
  },
  {
    company_id: '577bJcR33f45p&Z5q3cpq',
    quarter: 'Q122',
    cogs: 26,
    profit_margin: 0.648,
    revenue: 26.16848,
  },
  {
    company_id: '07ipYvIP7e64j&TGglpts',
    quarter: 'Q122',
    cogs: 153,
    profit_margin: 6.644,
    revenue: 163.16532,
  },
  {
    company_id: '428pIbM5Ss76y&VJpvxjq',
    quarter: 'Q122',
    cogs: 148,
    profit_margin: 11.987,
    revenue: 165.74076,
  },
  {
    company_id: '868hAXNXQe78f&XS9PSgn',
    quarter: 'Q122',
    cogs: 78,
    profit_margin: 2.013,
    revenue: 79.57014,
  },
  {
    company_id: '70f7ZcNATt29c&QFvRzng',
    quarter: 'Q122',
    cogs: 52,
    profit_margin: 8.063,
    revenue: 56.19276,
  },
  {
    company_id: '04okEhJSNt44u&HBXpzao',
    quarter: 'Q122',
    cogs: 69,
    profit_margin: 10.937,
    revenue: 76.54653,
  },
  {
    company_id: '62dtX9VX9l88z&YV0Uzoz',
    quarter: 'Q122',
    cogs: 89,
    profit_margin: 4.403,
    revenue: 92.91867,
  },
  {
    company_id: '910qTyP49b71q&MPlU6mr',
    quarter: 'Q122',
    cogs: 11,
    profit_margin: 2.547,
    revenue: 11.28017,
  },
  {
    company_id: '08x4TaL28u78k&AJtTfsw',
    quarter: 'Q122',
    cogs: 52,
    profit_margin: 8.663,
    revenue: 56.50476,
  },
  {
    company_id: '309dFEHPPk45a&QDWxwqp',
    quarter: 'Q122',
    cogs: 106,
    profit_margin: 4.91,
    revenue: 111.2046,
  },
  {
    company_id: '331hJRPXYr79o&M7G2bfr',
    quarter: 'Q122',
    cogs: 23,
    profit_margin: 0.214,
    revenue: 23.04922,
  },
  {
    company_id: '62KzUgS82v99c&CAtvbch',
    quarter: 'Q122',
    cogs: 117,
    profit_margin: 8.312,
    revenue: 126.72504,
  },
  {
    company_id: '47kfPhGVLn25p&GT0k6pk',
    quarter: 'Q122',
    cogs: 87,
    profit_margin: 2.628,
    revenue: 89.28636,
  },
  {
    company_id: '04R7LXR6Ia65a&VZCGyih',
    quarter: 'Q122',
    cogs: 80,
    profit_margin: 9.987,
    revenue: 87.9896,
  },
  {
    company_id: '23tCDNIO6r20t&ATAVNof',
    quarter: 'Q122',
    cogs: 102,
    profit_margin: 7.861,
    revenue: 110.01822,
  },
  {
    company_id: '25MAF3H85e61z&Z5XF6iv',
    quarter: 'Q122',
    cogs: 49,
    profit_margin: 2.054,
    revenue: 50.00646,
  },
  {
    company_id: '73umWxKTVi38d&J5mbqmx',
    quarter: 'Q122',
    cogs: 114,
    profit_margin: 8.466,
    revenue: 123.65124,
  },
  {
    company_id: '67NNCAFZMz76g&JTWWEoi',
    quarter: 'Q122',
    cogs: 11,
    profit_margin: 6.273,
    revenue: 11.69003,
  },
  {
    company_id: '08r7D1L16m59w&UVWnqcy',
    quarter: 'Q122',
    cogs: 156,
    profit_margin: 5.447,
    revenue: 164.49732,
  },
  {
    company_id: '96GeBHQRDr38c&D0PgGlr',
    quarter: 'Q122',
    cogs: 123,
    profit_margin: 10.073,
    revenue: 135.38979,
  },
  {
    company_id: '46knS6KGSv42k&M6Kysyi',
    quarter: 'Q122',
    cogs: 69,
    profit_margin: 9.906,
    revenue: 75.83514,
  },
  {
    company_id: '83LZWkH80z52j&N6qVGlj',
    quarter: 'Q122',
    cogs: 53,
    profit_margin: 0.299,
    revenue: 53.15847,
  },
  {
    company_id: '27X1B7HT4h19s&HUZmXek',
    quarter: 'Q122',
    cogs: 57,
    profit_margin: 2.049,
    revenue: 58.16793,
  },
  {
    company_id: '51Z8EhVQEm53v&KYb7ied',
    quarter: 'Q122',
    cogs: 50,
    profit_margin: 6.043,
    revenue: 53.0215,
  },
  {
    company_id: '59KjVfWVZv59g&JTaXorq',
    quarter: 'Q122',
    cogs: 104,
    profit_margin: 7.519,
    revenue: 111.81976,
  },
  {
    company_id: '79xnY9ZSHw42x&OGcsmsz',
    quarter: 'Q122',
    cogs: 119,
    profit_margin: 1.633,
    revenue: 120.94327,
  },
  {
    company_id: '52FpTXTY4a98l&B3jbfde',
    quarter: 'Q122',
    cogs: 127,
    profit_margin: 10.994,
    revenue: 140.96238,
  },
  {
    company_id: '08RkRmSV3s48w&DXngexw',
    quarter: 'Q122',
    cogs: 144,
    profit_margin: 4.072,
    revenue: 149.86368,
  },
  {
    company_id: '50mfIHZTKm51o&K2JTTih',
    quarter: 'Q122',
    cogs: 95,
    profit_margin: 11.202,
    revenue: 105.6419,
  },
  {
    company_id: '01fsNyJEDs52b&X0kXMwm',
    quarter: 'Q122',
    cogs: 128,
    profit_margin: 11.564,
    revenue: 142.80192,
  },
  {
    company_id: '73idM7QP4o66t&JMmL4ai',
    quarter: 'Q122',
    cogs: 25,
    profit_margin: 3.763,
    revenue: 25.94075,
  },
  {
    company_id: '93srUSL1Yt42j&KSlsVpb',
    quarter: 'Q122',
    cogs: 77,
    profit_margin: 4.083,
    revenue: 80.14391,
  },
  {
    company_id: '29CPLQZX7l27l&ATXLyth',
    quarter: 'Q122',
    cogs: 98,
    profit_margin: 7.237,
    revenue: 105.09226,
  },
  {
    company_id: '70EADpH7Hg39g&BUqA6cz',
    quarter: 'Q122',
    cogs: 102,
    profit_margin: 0.843,
    revenue: 102.85986,
  },
  {
    company_id: '43h5VGVUEi65v&BNxpCtd',
    quarter: 'Q122',
    cogs: 51,
    profit_margin: 7.79,
    revenue: 54.9729,
  },
  {
    company_id: '87N2BZIELb65b&MOChEjy',
    quarter: 'Q122',
    cogs: 116,
    profit_margin: 1.689,
    revenue: 117.95924,
  },
  {
    company_id: '50uwRmJP0r92g&XLGoIlf',
    quarter: 'Q122',
    cogs: 94,
    profit_margin: 9.66,
    revenue: 103.0804,
  },
  {
    company_id: '04CXGBD95p64j&GFsHzvf',
    quarter: 'Q122',
    cogs: 36,
    profit_margin: 4.046,
    revenue: 37.45656,
  },
  {
    company_id: '80IvXlPHJo49z&FHORuqr',
    quarter: 'Q122',
    cogs: 39,
    profit_margin: 4.947,
    revenue: 40.92933,
  },
  {
    company_id: '85bSJLHJ5s79o&DDEMGej',
    quarter: 'Q122',
    cogs: 154,
    profit_margin: 0.585,
    revenue: 154.9009,
  },
  {
    company_id: '56FbAoF7Td09a&WO4mOlk',
    quarter: 'Q122',
    cogs: 19,
    profit_margin: 11.567,
    revenue: 21.19773,
  },
  {
    company_id: '04hlFAJB4f44l&BTr83se',
    quarter: 'Q122',
    cogs: 46,
    profit_margin: 4.749,
    revenue: 48.18454,
  },
  {
    company_id: '83okZLL6Yw26b&X41lsvr',
    quarter: 'Q122',
    cogs: 99,
    profit_margin: 9.198,
    revenue: 108.10602,
  },
  {
    company_id: '33QARoW9Jk32a&LWSjenb',
    quarter: 'Q122',
    cogs: 44,
    profit_margin: 8.5,
    revenue: 47.74,
  },
  {
    company_id: '42BRYEJNWl10r&N0WA7ol',
    quarter: 'Q122',
    cogs: 13,
    profit_margin: 11.47,
    revenue: 14.4911,
  },
  {
    company_id: '056qHnE87u36l&KDxSwxn',
    quarter: 'Q122',
    cogs: 47,
    profit_margin: 8.323,
    revenue: 50.91181,
  },
  {
    company_id: '79aZGAET2g29f&VJis6nj',
    quarter: 'Q122',
    cogs: 80,
    profit_margin: 5.526,
    revenue: 84.4208,
  },
  {
    company_id: '9986DuWY1j97c&U0GLgio',
    quarter: 'Q122',
    cogs: 103,
    profit_margin: 6.485,
    revenue: 109.67955,
  },
  {
    company_id: '37wmWQCCZp61x&TOjaIzn',
    quarter: 'Q122',
    cogs: 63,
    profit_margin: 4.908,
    revenue: 66.09204,
  },
  {
    company_id: '21IyLCU9Mj23n&YFs0zno',
    quarter: 'Q122',
    cogs: 130,
    profit_margin: 8.722,
    revenue: 141.3386,
  },
  {
    company_id: '06gISyNBJz59v&KWDIAjb',
    quarter: 'Q122',
    cogs: 142,
    profit_margin: 8.304,
    revenue: 153.79168,
  },
  {
    company_id: '46s1XpUKKn53u&XWT5vir',
    quarter: 'Q122',
    cogs: 18,
    profit_margin: 4.452,
    revenue: 18.80136,
  },
  {
    company_id: '92AWJaTG8d09a&V8MOTew',
    quarter: 'Q122',
    cogs: 143,
    profit_margin: 0.571,
    revenue: 143.81653,
  },
  {
    company_id: '94cWX6LWOf35e&IP5WRix',
    quarter: 'Q122',
    cogs: 21,
    profit_margin: 5.374,
    revenue: 22.12854,
  },
  {
    company_id: '32uYVnR21e34g&CWi72go',
    quarter: 'Q122',
    cogs: 54,
    profit_margin: 10.19,
    revenue: 59.5026,
  },
  {
    company_id: '37zoFSZ0Qp21b&KIdHmia',
    quarter: 'Q122',
    cogs: 136,
    profit_margin: 0.644,
    revenue: 136.87584,
  },
  {
    company_id: '0196K6DELx87x&C16Mxue',
    quarter: 'Q122',
    cogs: 132,
    profit_margin: 5.343,
    revenue: 139.05276,
  },
  {
    company_id: '49uTYIALKv36c&IMfFGho',
    quarter: 'Q122',
    cogs: 119,
    profit_margin: 5.523,
    revenue: 125.57237,
  },
  {
    company_id: '98TkZdFYDm27z&SEP61wf',
    quarter: 'Q122',
    cogs: 83,
    profit_margin: 0.848,
    revenue: 83.70384,
  },
  {
    company_id: '75thXYSTSt13u&R9VIEtb',
    quarter: 'Q122',
    cogs: 128,
    profit_margin: 4.281,
    revenue: 133.47968,
  },
  {
    company_id: '01HaCOUE4u11b&G4NpYns',
    quarter: 'Q122',
    cogs: 113,
    profit_margin: 11.558,
    revenue: 126.06054,
  },
  {
    company_id: '24ObOmV14d68x&CKRzzdu',
    quarter: 'Q122',
    cogs: 106,
    profit_margin: 6.666,
    revenue: 113.06596,
  },
  {
    company_id: '78VLC4RK7u54c&E4cYDxs',
    quarter: 'Q122',
    cogs: 53,
    profit_margin: 1.787,
    revenue: 53.94711,
  },
  {
    company_id: '2721TSRQKs74b&ITIsPwk',
    quarter: 'Q122',
    cogs: 70,
    profit_margin: 10.849,
    revenue: 77.5943,
  },
  {
    company_id: '02iEPuHXUe30m&WAjyazb',
    quarter: 'Q122',
    cogs: 136,
    profit_margin: 0.087,
    revenue: 136.11832,
  },
  {
    company_id: '62K5FzHLTz46t&MRCe0sm',
    quarter: 'Q122',
    cogs: 100,
    profit_margin: 3.864,
    revenue: 103.864,
  },
  {
    company_id: '98ZfSVVC8q34w&VJ36qcx',
    quarter: 'Q122',
    cogs: 23,
    profit_margin: 6.039,
    revenue: 24.38897,
  },
  {
    company_id: '23rRVxB4Cg76j&J3dMyal',
    quarter: 'Q122',
    cogs: 83,
    profit_margin: 6.735,
    revenue: 88.59005,
  },
  {
    company_id: '87XnAhJDFp70e&Q4jwgxs',
    quarter: 'Q122',
    cogs: 153,
    profit_margin: 7.758,
    revenue: 164.86974,
  },
  {
    company_id: '40v8F0NIYr72v&ZCQETgf',
    quarter: 'Q122',
    cogs: 115,
    profit_margin: 9.279,
    revenue: 125.67085,
  },
  {
    company_id: '39RpBmNQUi74u&MBAsNvn',
    quarter: 'Q122',
    cogs: 50,
    profit_margin: 2.664,
    revenue: 51.332,
  },
  {
    company_id: '72GQBpJOFv27j&FYQJLra',
    quarter: 'Q122',
    cogs: 35,
    profit_margin: 2.447,
    revenue: 35.85645,
  },
  {
    company_id: '39ckZ3XONk29k&XBE15zr',
    quarter: 'Q122',
    cogs: 156,
    profit_margin: 9.985,
    revenue: 171.5766,
  },
];
const employees = [
  {
    first_name: 'Mahala',
    last_name: 'Walford',
    email: 'mwalford0@spotify.com',
    avatar:
      'https://robohash.org/sitconsequaturconsequatur.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Quality Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Desirae',
    last_name: 'Pitkin',
    email: 'dpitkin1@pcworld.com',
    avatar: 'https://robohash.org/fugiatquiexplicabo.png?size=50x50&set=set1',
    department: 'Marketing',
    title: 'Database Administrator III',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Gordy',
    last_name: 'Salzberger',
    email: 'gsalzberger2@imageshack.us',
    avatar: 'https://robohash.org/velitabenim.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Web Designer IV',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Annadiane',
    last_name: 'Hirsthouse',
    email: 'ahirsthouse3@irs.gov',
    avatar:
      'https://robohash.org/reprehenderitautofficiis.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Financial Advisor',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Syman',
    last_name: 'Le Fevre',
    email: 'slefevre4@indiegogo.com',
    avatar:
      'https://robohash.org/aspernaturaccusantiumet.png?size=50x50&set=set1',
    department: 'Research and Development',
    title: 'General Manager',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Willow',
    last_name: 'Dober',
    email: 'wdober5@abc.net.au',
    avatar:
      'https://robohash.org/distinctioquibusdamillum.png?size=50x50&set=set1',
    department: 'Support',
    title: 'Senior Cost Accountant',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Maryann',
    last_name: 'Hourahan',
    email: 'mhourahan6@comsenz.com',
    avatar: 'https://robohash.org/eoseaet.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Chemical Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Benoit',
    last_name: 'Terbrugge',
    email: 'bterbrugge7@myspace.com',
    avatar: 'https://robohash.org/occaecatinonsed.png?size=50x50&set=set1',
    department: 'Research and Development',
    title: 'Geological Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Cecilio',
    last_name: 'Crathern',
    email: 'ccrathern8@nasa.gov',
    avatar: 'https://robohash.org/molestiasitaquererum.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Web Designer I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Vaughan',
    last_name: 'Antonowicz',
    email: 'vantonowicz9@soundcloud.com',
    avatar: 'https://robohash.org/quiidaut.png?size=50x50&set=set1',
    department: 'Services',
    title: 'GIS Technical Architect',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Cyrillus',
    last_name: 'Brotherhead',
    email: 'cbrotherheada@cornell.edu',
    avatar: 'https://robohash.org/omnisestaut.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Health Coach I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Hamid',
    last_name: 'Renbold',
    email: 'hrenboldb@google.cn',
    avatar: 'https://robohash.org/rerumquilaudantium.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Software Test Engineer II',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Joceline',
    last_name: 'Dyhouse',
    email: 'jdyhousec@umn.edu',
    avatar: 'https://robohash.org/cumqueestdolor.png?size=50x50&set=set1',
    department: 'Services',
    title: 'Business Systems Development Analyst',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Bethena',
    last_name: 'Blakiston',
    email: 'bblakistond@google.it',
    avatar:
      'https://robohash.org/nostrumsimiliquenecessitatibus.png?size=50x50&set=set1',
    department: 'Training',
    title: 'Media Manager II',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Frank',
    last_name: 'Kment',
    email: 'fkmente@tripadvisor.com',
    avatar: 'https://robohash.org/namquoomnis.png?size=50x50&set=set1',
    department: 'Human Resources',
    title: 'Paralegal',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Cecelia',
    last_name: 'Jepson',
    email: 'cjepsonf@princeton.edu',
    avatar: 'https://robohash.org/velmolestiaeipsam.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Design Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Cordula',
    last_name: 'Sokale',
    email: 'csokaleg@hud.gov',
    avatar: 'https://robohash.org/sednisivel.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Senior Sales Associate',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Rab',
    last_name: 'McAuslene',
    email: 'rmcausleneh@sitemeter.com',
    avatar: 'https://robohash.org/dolortemporaporro.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Teacher',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Codi',
    last_name: 'Elton',
    email: 'celtoni@pen.io',
    avatar: 'https://robohash.org/debitisquoslabore.png?size=50x50&set=set1',
    department: 'Support',
    title: 'Mechanical Systems Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Korrie',
    last_name: 'Camidge',
    email: 'kcamidgej@free.fr',
    avatar: 'https://robohash.org/autvoluptasveniam.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Structural Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Arlinda',
    last_name: 'Markl',
    email: 'amarklk@answers.com',
    avatar: 'https://robohash.org/aliquamnumquamrerum.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Information Systems Manager',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Dave',
    last_name: 'Alker',
    email: 'dalkerl@ibm.com',
    avatar:
      'https://robohash.org/illumaperiamexercitationem.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Account Coordinator',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Lorain',
    last_name: 'Espie',
    email: 'lespiem@fema.gov',
    avatar: 'https://robohash.org/molestiasliberovel.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Administrative Officer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Maryjane',
    last_name: 'Cartwight',
    email: 'mcartwightn@examiner.com',
    avatar:
      'https://robohash.org/pariaturconsectetursimilique.png?size=50x50&set=set1',
    department: 'Services',
    title: 'Nuclear Power Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Andrea',
    last_name: 'Jeannin',
    email: 'ajeannino@shutterfly.com',
    avatar: 'https://robohash.org/admaioresratione.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Safety Technician IV',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Ame',
    last_name: 'Carrane',
    email: 'acarranep@nationalgeographic.com',
    avatar: 'https://robohash.org/utnondolorem.png?size=50x50&set=set1',
    department: 'Services',
    title: 'Programmer Analyst II',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Fax',
    last_name: 'Chritchley',
    email: 'fchritchleyq@si.edu',
    avatar: 'https://robohash.org/sitinventorequae.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Help Desk Operator',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Mariam',
    last_name: 'Brandi',
    email: 'mbrandir@ucoz.com',
    avatar:
      'https://robohash.org/magnamreiciendisreprehenderit.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Operator',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Rosaleen',
    last_name: 'Medhurst',
    email: 'rmedhursts@abc.net.au',
    avatar: 'https://robohash.org/occaecatietvero.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Business Systems Development Analyst',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Lola',
    last_name: 'MacKnocker',
    email: 'lmacknockert@howstuffworks.com',
    avatar: 'https://robohash.org/evenietquiaut.png?size=50x50&set=set1',
    department: 'Training',
    title: 'Environmental Specialist',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Joey',
    last_name: 'Dunne',
    email: 'jdunneu@mac.com',
    avatar: 'https://robohash.org/suntnumquamest.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Database Administrator III',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Teressa',
    last_name: 'Gauld',
    email: 'tgauldv@discovery.com',
    avatar:
      'https://robohash.org/eaqueperspiciatisesse.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Human Resources Assistant I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Cullan',
    last_name: 'Reaper',
    email: 'creaperw@miibeian.gov.cn',
    avatar: 'https://robohash.org/atqueestitaque.png?size=50x50&set=set1',
    department: 'Product Management',
    title: 'Registered Nurse',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Francis',
    last_name: 'Giacobazzi',
    email: 'fgiacobazzix@chicagotribune.com',
    avatar: 'https://robohash.org/autemsitmollitia.png?size=50x50&set=set1',
    department: 'Marketing',
    title: 'Professor',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Creight',
    last_name: 'Crandon',
    email: 'ccrandony@dion.ne.jp',
    avatar: 'https://robohash.org/temporibusipsumqui.png?size=50x50&set=set1',
    department: 'Product Management',
    title: 'VP Sales',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Jard',
    last_name: 'Smallman',
    email: 'jsmallmanz@t-online.de',
    avatar:
      'https://robohash.org/quasperspiciatisofficia.png?size=50x50&set=set1',
    department: 'Support',
    title: 'Staff Scientist',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Veronica',
    last_name: 'Stonner',
    email: 'vstonner10@about.com',
    avatar: 'https://robohash.org/quisnesciuntcumque.png?size=50x50&set=set1',
    department: 'Research and Development',
    title: 'Account Representative I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Tamarra',
    last_name: 'Jedrysik',
    email: 'tjedrysik11@businesswire.com',
    avatar: 'https://robohash.org/illumauttenetur.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Analog Circuit Design manager',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Pacorro',
    last_name: 'Craker',
    email: 'pcraker12@fastcompany.com',
    avatar: 'https://robohash.org/sedipsumnon.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Data Coordiator',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Bruis',
    last_name: 'Ricciardello',
    email: 'bricciardello13@technorati.com',
    avatar: 'https://robohash.org/sapienteomnisdebitis.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Programmer I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Emeline',
    last_name: 'Fullman',
    email: 'efullman14@simplemachines.org',
    avatar: 'https://robohash.org/solutanisised.png?size=50x50&set=set1',
    department: 'Research and Development',
    title: 'Geological Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Jareb',
    last_name: 'Froschauer',
    email: 'jfroschauer15@globo.com',
    avatar: 'https://robohash.org/insintlaborum.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Database Administrator IV',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Marcelle',
    last_name: 'Jeakins',
    email: 'mjeakins16@tamu.edu',
    avatar: 'https://robohash.org/veloditerror.png?size=50x50&set=set1',
    department: 'Human Resources',
    title: 'Developer IV',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Agnes',
    last_name: 'Aubury',
    email: 'aaubury17@github.com',
    avatar: 'https://robohash.org/suntrerumet.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Technical Writer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Dianne',
    last_name: 'Reiach',
    email: 'dreiach18@godaddy.com',
    avatar: 'https://robohash.org/modirationeeum.png?size=50x50&set=set1',
    department: 'Marketing',
    title: 'Mechanical Systems Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Georgianne',
    last_name: 'Widd',
    email: 'gwidd19@shutterfly.com',
    avatar:
      'https://robohash.org/doloremvoluptatemmaxime.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Structural Analysis Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Jacky',
    last_name: 'Brann',
    email: 'jbrann1a@businesswire.com',
    avatar: 'https://robohash.org/veniamiuresuscipit.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Physical Therapy Assistant',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Clarie',
    last_name: 'Haydn',
    email: 'chaydn1b@xinhuanet.com',
    avatar: 'https://robohash.org/nihilautminima.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Administrative Officer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Wallas',
    last_name: 'Huddles',
    email: 'whuddles1c@bizjournals.com',
    avatar: 'https://robohash.org/autabquas.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Accountant IV',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Gerrie',
    last_name: 'Florence',
    email: 'gflorence1d@umich.edu',
    avatar: 'https://robohash.org/officiaestcorporis.png?size=50x50&set=set1',
    department: 'Marketing',
    title: 'Sales Associate',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Evin',
    last_name: 'Crystal',
    email: 'ecrystal1e@patch.com',
    avatar: 'https://robohash.org/etreiciendisut.png?size=50x50&set=set1',
    department: 'Services',
    title: 'Electrical Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Jarvis',
    last_name: 'Redier',
    email: 'jredier1f@gnu.org',
    avatar:
      'https://robohash.org/necessitatibusmaximefacere.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Nuclear Power Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Heath',
    last_name: 'Baccup',
    email: 'hbaccup1g@macromedia.com',
    avatar: 'https://robohash.org/quitotamdoloribus.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Editor',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Modesta',
    last_name: 'Nash',
    email: 'mnash1h@facebook.com',
    avatar: 'https://robohash.org/magnamquodautem.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Chemical Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Tirrell',
    last_name: 'Baitey',
    email: 'tbaitey1i@msn.com',
    avatar: 'https://robohash.org/quiaquimolestias.png?size=50x50&set=set1',
    department: 'Services',
    title: 'Chief Design Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Jilleen',
    last_name: 'Benjefield',
    email: 'jbenjefield1j@github.io',
    avatar: 'https://robohash.org/rerumoptioblanditiis.png?size=50x50&set=set1',
    department: 'Marketing',
    title: 'Statistician II',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Rhianon',
    last_name: 'Ropartz',
    email: 'rropartz1k@si.edu',
    avatar: 'https://robohash.org/etpariaturautem.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Administrative Officer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Kristoforo',
    last_name: 'Danell',
    email: 'kdanell1l@guardian.co.uk',
    avatar: 'https://robohash.org/temporibusutiusto.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Technical Writer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Aymer',
    last_name: 'Scarff',
    email: 'ascarff1m@mozilla.org',
    avatar:
      'https://robohash.org/laborerepellenduscorrupti.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Web Developer I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Liza',
    last_name: 'Merrisson',
    email: 'lmerrisson1n@usa.gov',
    avatar: 'https://robohash.org/dictarerumrerum.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Accountant IV',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Hubey',
    last_name: 'Drugan',
    email: 'hdrugan1o@bizjournals.com',
    avatar:
      'https://robohash.org/molestiaeipsummolestiae.png?size=50x50&set=set1',
    department: 'Services',
    title: 'Structural Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Hunt',
    last_name: 'Rowlatt',
    email: 'hrowlatt1p@springer.com',
    avatar: 'https://robohash.org/dolorumquoaperiam.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Actuary',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Georgia',
    last_name: 'Lindblad',
    email: 'glindblad1q@arizona.edu',
    avatar: 'https://robohash.org/expeditanequeet.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Design Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Jobina',
    last_name: 'Sive',
    email: 'jsive1r@xrea.com',
    avatar: 'https://robohash.org/autlaboriosamsit.png?size=50x50&set=set1',
    department: 'Training',
    title: 'Chief Design Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Morgun',
    last_name: 'Smitham',
    email: 'msmitham1s@eepurl.com',
    avatar: 'https://robohash.org/quidebitisnostrum.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Database Administrator I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Noellyn',
    last_name: 'Avison',
    email: 'navison1t@independent.co.uk',
    avatar:
      'https://robohash.org/mollitiamolestiaeinventore.png?size=50x50&set=set1',
    department: 'Product Management',
    title: 'Pharmacist',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Darb',
    last_name: "O'Dulchonta",
    email: 'dodulchonta1u@ning.com',
    avatar: 'https://robohash.org/undedoloremducimus.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Teacher',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Eric',
    last_name: 'Lambell',
    email: 'elambell1v@virginia.edu',
    avatar:
      'https://robohash.org/estprovidentoccaecati.png?size=50x50&set=set1',
    department: 'Human Resources',
    title: 'Biostatistician I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Masha',
    last_name: 'Emsden',
    email: 'memsden1w@reverbnation.com',
    avatar: 'https://robohash.org/doloritaqueharum.png?size=50x50&set=set1',
    department: 'Support',
    title: 'VP Accounting',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Lars',
    last_name: 'Isitt',
    email: 'lisitt1x@infoseek.co.jp',
    avatar: 'https://robohash.org/earumabofficia.png?size=50x50&set=set1',
    department: 'Marketing',
    title: 'Software Test Engineer III',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Ezmeralda',
    last_name: 'Klimschak',
    email: 'eklimschak1y@furl.net',
    avatar: 'https://robohash.org/beataerecusandaerem.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Automation Specialist IV',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Tanney',
    last_name: 'Kneafsey',
    email: 'tkneafsey1z@bing.com',
    avatar: 'https://robohash.org/eumsuntexcepturi.png?size=50x50&set=set1',
    department: 'Training',
    title: 'Compensation Analyst',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Juliann',
    last_name: 'Fowles',
    email: 'jfowles20@google.nl',
    avatar:
      'https://robohash.org/quoexercitationemfugit.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'General Manager',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Giustina',
    last_name: 'Armin',
    email: 'garmin21@networkadvertising.org',
    avatar: 'https://robohash.org/ametutquia.png?size=50x50&set=set1',
    department: 'Support',
    title: 'Nurse',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Pauline',
    last_name: 'Copello',
    email: 'pcopello22@latimes.com',
    avatar: 'https://robohash.org/remnonvoluptatibus.png?size=50x50&set=set1',
    department: 'Human Resources',
    title: 'Civil Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Randell',
    last_name: 'Mease',
    email: 'rmease23@uol.com.br',
    avatar:
      'https://robohash.org/rerumdoloresaccusamus.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Actuary',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Maribelle',
    last_name: 'While',
    email: 'mwhile24@google.ru',
    avatar: 'https://robohash.org/idvoluptatemodit.png?size=50x50&set=set1',
    department: 'Human Resources',
    title: 'Database Administrator III',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Etty',
    last_name: 'Tebbut',
    email: 'etebbut25@freewebs.com',
    avatar: 'https://robohash.org/nonvoluptatemut.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Librarian',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Cheslie',
    last_name: 'Dyton',
    email: 'cdyton26@desdev.cn',
    avatar: 'https://robohash.org/illooditsed.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Statistician IV',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Leora',
    last_name: 'Truscott',
    email: 'ltruscott27@imdb.com',
    avatar: 'https://robohash.org/recusandaeetcumque.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Geological Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Neila',
    last_name: 'Merrisson',
    email: 'nmerrisson28@comsenz.com',
    avatar: 'https://robohash.org/saepereiciendisfugit.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Payment Adjustment Coordinator',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Osbourn',
    last_name: 'Storrar',
    email: 'ostorrar29@freewebs.com',
    avatar: 'https://robohash.org/quieosnam.png?size=50x50&set=set1',
    department: 'Business Development',
    title: 'Occupational Therapist',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Stace',
    last_name: 'Conkling',
    email: 'sconkling2a@bloomberg.com',
    avatar: 'https://robohash.org/quiseumut.png?size=50x50&set=set1',
    department: 'Research and Development',
    title: 'Environmental Specialist',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Grove',
    last_name: 'Hellmore',
    email: 'ghellmore2b@wikimedia.org',
    avatar: 'https://robohash.org/undecumquenam.png?size=50x50&set=set1',
    department: 'Support',
    title: 'Media Manager I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Horatius',
    last_name: 'Loxley',
    email: 'hloxley2c@stanford.edu',
    avatar: 'https://robohash.org/omnisdoloraut.png?size=50x50&set=set1',
    department: 'Sales',
    title: 'Dental Hygienist',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Florette',
    last_name: 'Rosenbusch',
    email: 'frosenbusch2d@shop-pro.jp',
    avatar: 'https://robohash.org/etquisa.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Financial Advisor',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Tedie',
    last_name: 'Elder',
    email: 'telder2e@domainmarket.com',
    avatar: 'https://robohash.org/estillorecusandae.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Speech Pathologist',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Nicolina',
    last_name: 'Peach',
    email: 'npeach2f@washingtonpost.com',
    avatar: 'https://robohash.org/abaliquidnihil.png?size=50x50&set=set1',
    department: 'Training',
    title: 'Electrical Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Alyosha',
    last_name: 'Camilleri',
    email: 'acamilleri2g@spotify.com',
    avatar:
      'https://robohash.org/accusamusvoluptatemsequi.png?size=50x50&set=set1',
    department: 'Human Resources',
    title: 'Software Engineer III',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Anders',
    last_name: 'Davidy',
    email: 'adavidy2h@canalblog.com',
    avatar: 'https://robohash.org/autodionobis.png?size=50x50&set=set1',
    department: 'Accounting',
    title: 'Editor',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Deina',
    last_name: 'Hatfield',
    email: 'dhatfield2i@miitbeian.gov.cn',
    avatar: 'https://robohash.org/evenietaliquidut.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Systems Administrator IV',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Jobey',
    last_name: 'Manktelow',
    email: 'jmanktelow2j@usda.gov',
    avatar:
      'https://robohash.org/laudantiumenimnecessitatibus.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Geologist I',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Hildy',
    last_name: 'Krolak',
    email: 'hkrolak2k@latimes.com',
    avatar: 'https://robohash.org/distinctiositet.png?size=50x50&set=set1',
    department: 'Support',
    title: 'Structural Analysis Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Uriel',
    last_name: 'Court',
    email: 'ucourt2l@trellian.com',
    avatar:
      'https://robohash.org/explicaboassumendaquia.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Desktop Support Technician',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Rosabel',
    last_name: 'Chugg',
    email: 'rchugg2m@twitter.com',
    avatar: 'https://robohash.org/maximenequequo.png?size=50x50&set=set1',
    department: 'Product Management',
    title: 'Recruiting Manager',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Carolyn',
    last_name: 'Nannetti',
    email: 'cnannetti2n@va.gov',
    avatar: 'https://robohash.org/eosessesed.png?size=50x50&set=set1',
    department: 'Services',
    title: 'Help Desk Operator',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Carlen',
    last_name: 'Innman',
    email: 'cinnman2o@prlog.org',
    avatar: 'https://robohash.org/hiceaquenihil.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Senior Quality Engineer',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Sarette',
    last_name: 'Rudiger',
    email: 'srudiger2p@mail.ru',
    avatar:
      'https://robohash.org/idsolutanecessitatibus.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Sales Associate',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Inez',
    last_name: 'Chisholme',
    email: 'ichisholme2q@weebly.com',
    avatar: 'https://robohash.org/fugalaborumdicta.png?size=50x50&set=set1',
    department: 'Legal',
    title: 'Paralegal',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
  {
    first_name: 'Alice',
    last_name: 'Niblock',
    email: 'aniblock2r@facebook.com',
    avatar: 'https://robohash.org/voluptateaerror.png?size=50x50&set=set1',
    department: 'Engineering',
    title: 'Actuary',
    company_id: '21ImC8IUCp19m&QEfdBbg',
  },
];

module.exports = {
  companies,
  financials,
  employees,
};
